### ISSUE TITLE
Variable reference 'makeStatePath' is unbound at api-scala-sifive/scala.wake:19:[16-28]

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#39]
I've been trying to run/build the entire block-pio project example. I've followed the steps prescribed in readme and the following error occurs while executing the run command < wake 'runSim ${dut plan}' >

Error Message: 
```
Variable reference 'makeStatePath' is unbound at api-scala-sifive/scala.wake:19:[16-28]
Type error; function <command-line>:1:[1-8] expected argument 'argument' of type:
    RocketChipDUTPlan
  but was supplied argument src/parser.cpp:389:1 of type:
    String
>>> Aborting without execution <<<
```

Wake tool's tutorial describes cause of this error as follows:

_"Wake processes all versioned wake files (*.wake) which are in the workspace. A very common mistake is to create a new wake file and run wake without first adding that file to version control. In that case, the file will not be read, and you will likely get an error like **Variable reference xyz is unbound.**"_

How do I fix this?

**Comment by sistillson** [comment]
It's likely that you need to use a version of wake with the `makeStatePath` function defined.

You probably need to use wake v0.17.

**Comment by saurabhsingh-pvips** [comment]
I was using v0.18.xxxx previously. As per your suggestion, I downgraded to v0.17 but the issue is still unresolved.

**Comment by jackkoenig** [comment]
You actually need `0.15.x`, sorry about that, we need to upgrade

**Comment by saurabhsingh-pvips** [comment]
Downgrading to `v0.15.x` did fix the described issue but added 3 more 'unbound' issues:

`Primitive reference catch is unbound at ../../../usr/local/share/wake/lib/core/exception.wake:3:[15-26]
Primitive reference raise is unbound at ../../../usr/local/share/wake/lib/core/exception.wake:6:[22-33]
Primitive reference test is unbound at ../../../usr/local/share/wake/lib/core/exception.wake:2:[15-25]`

Additional Comment:

I tried looking into the issue and I've realized I am unable to run any wake scripts. It seems an issue of  wake v0.15.x .

**Comment by richardxia** [comment]
@saurabhsingh-pvips, it doesn't look like you are actually using wake 0.15.x, as `exception.wake` no longer exists in the `v0.15` branch. You can confirm by checking the source tree at v0.15.0: https://github.com/sifive/wake/tree/v0.15.0/share/wake/lib/core

Can you double check the version of wake that you are using?

**Comment by saurabhsingh-pvips** [comment]
I did double check the wake version. Here you go:
![image](https://user-images.githubusercontent.com/57518239/68786844-7ce47800-0666-11ea-99c3-2cbac3c50714.png)

I downgraded from `v0.18.x`. Is it possible that `exception.wake` is a residue of previous version?

**Comment by richardxia** [comment]
Your installation must be in an inconsistent state, as `exception.wake` should not have existed in 0.15, 0.16. 0.17, or 0.18a. Are you installing from source or are you using one of the precompiled binary releases? If you are installing from source, please try removing all of the files that installs prior to installing a newer version.
