### ISSUE TITLE
`panic_called failed at src/exception.cpp

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#42]
I've been trying to run the block-pio example for a while now. As instructed in the Readme, firing the command `wake 'runSim pioDUT'` fails with following errors:

```
<ivycache> ivycache
protoc --java_out=build/firrtl/proto firrtl/src/main/proto/firrtl.proto
execve protoc: No such file or directory
WARNING: Could not parse DTS JSON: _root_.sifive.skeleton.DefaultConfig_sifive.skeleton.WithSimUART_sifive.skeleton.WithTestFinisher_sifive.blocks.pio.WithpioTop.json file not found
PANIC: Error "File not found" Nil
Requirement !panic_called failed at src/exception.cpp:64
```
Google look up suggest Missing protobuf but reinstalling protobuf doesn't help. Warning persists.

It appears to me as if the `build.wake` in `soc-testsocket-sifive` fails to import the `WithpioTop..json `file or the file is missing. 

Help?

**UPDATE:** 
Tried resolving the `execve protoc: No such file or directory` by reinstalling the latest protocbuf via [here](https://github.com/protocolbuffers/protobuf). That error was resolved but process stuck at this now:

```
<ivycache> ivycache
api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/firrtl.json.template -c build/api-scala-sifive/bloop/firrtl.json -b scala --coursier-cache ivycache --bloop-args compile -c build/api-scala-sifive/bloop firrtl --jar build/firrtl/scala-2.12/jar/firrtl.jar
[   #  ] api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/firrtl.json.template -c build/api-scala-sifive/bloo ... ycache --bloop-args compile -c build/api-scala-sifive/bloop firrtl --jar build/firrtl/scala-2.12/jar/firrtl.jar
[E] [E10] ../firrtl/proto/firrtl/FirrtlProtos.java:5497:55
[E]       type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage
[E]       L5497:                   com.google.protobuf.AbstractMessage.InternalOneOfEnum {
[E]                                                                    ^
[E] [E9] ../firrtl/proto/firrtl/FirrtlProtos.java:38372:51
[E]      type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage
[E]      L38372:               com.google.protobuf.AbstractMessage.InternalOneOfEnum {
[E]                                                                ^
[E] [E8] ../firrtl/proto/firrtl/FirrtlProtos.java:28022:51
[E]      type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage
[E]      L28022:               com.google.protobuf.AbstractMessage.InternalOneOfEnum {
[E]                                                                ^
[E] [E7] ../firrtl/proto/firrtl/FirrtlProtos.java:13297:53
[E]      type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage
[E]      L13297:                 com.google.protobuf.AbstractMessage.InternalOneOfEnum {
[E]                                                                  ^
[E] [E6] ../firrtl/proto/firrtl/FirrtlProtos.java:16040:53
[E]      type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage
[E]      L16040:                 com.google.protobuf.AbstractMessage.InternalOneOfEnum {
[E]                                                                  ^
[E] [E5] ../firrtl/proto/firrtl/FirrtlProtos.java:52425:51
[E]      type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage
[E]      L52425:               com.google.protobuf.AbstractMessage.InternalOneOfEnum {
[E]                                                                ^
[E] [E4] ../firrtl/proto/firrtl/FirrtlProtos.java:1758:51
[E]      type InternalOneOfEnum is not a member of com.google.protobuf.AbstractMessage
[E]      L1758:               com.google.protobuf.AbstractMessage.InternalOneOfEnum {
[E]                                                               ^
[E] ../../firrtl/src/main/scala/firrtl/RenameMap.scala: L76 [E1], L77 [E2], L78 [E3]
[E] ../firrtl/proto/firrtl/FirrtlProtos.java: L1758 [E4], L5497 [E10], L13297 [E7], L16040 [E6], L28022 [E8], L38372 [E9], L52425 [E5]
[E] 'firrtl' failed to compile.
Scala compilation failed for 'api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/firrtl.json.template -c build/api-scala-sifive/bloop/firrtl.json -b scala --coursier-cache ivycache --bloop-args "compile -c build/api-scala-sifive/bloop firrtl" --jar build/firrtl/scala-2.12/jar/firrtl.jar'
WARNING: Could not parse DTS JSON: _root_.sifive.skeleton.DefaultConfig_sifive.skeleton.WithSimUART_sifive.skeleton.WithTestFinisher_sifive.blocks.pio.WithpioTop.json file not found
PANIC: Error "File not found" Nil
Requirement !panic_called failed at src/exception.cpp:64
```
Reffering the issue [here](https://github.com/sifive/api-firrtl-sifive/issues/6). The suggestion to use `v3.6.1` failed for me. I downgraded from the latest protoc `v3.11` to `v3.6.1`.

**Comment by jackkoenig** [comment]
Try `protoc` `3.5.1`.

Basically there are two pieces to the Protobuf dependency:
1. `protoc` which api-firrtl-sifive requests as version `3.5.1` [here](https://github.com/sifive/api-firrtl-sifive/blob/4977bbeeadc350e2e1290237d17dd1baf77013f8/build.wake#L29)
2. `protobuf-java` runtime dependency which is specified as `3.5.0` [here](https://github.com/sifive/api-firrtl-sifive/blob/4977bbeeadc350e2e1290237d17dd1baf77013f8/ivydependencies.json#L12)

It would be ideal if we could find a better way to deal with this mismatch in `api-firrtl-sifive`... It could check the version of `protoc` against the java runtime version. I'll file an issue.

**Comment by saurabhsingh-pvips** [comment]
I did try using protoc v3.5.1 but it doesn't fix the problem.

![image](https://user-images.githubusercontent.com/57518239/69212189-96198700-0b86-11ea-9226-c2fca716f97c.png)

The entire error message is same except this:
In `v3.6.1`:
`[E] ../firrtl/proto/firrtl/FirrtlProtos.java: L1758 [E4], L5497 [E10], L13297 [E7], L16040 [E6], L28022 [E8], L38372 [E9], L52425 [E5]`

In `v3.5.1`:
`[E] ../firrtl/proto/firrtl/FirrtlProtos.java: L1758 [E4], L5497 [E10], L13297 [E7], L16040 [E6], L28022 [E8], L38372 [E9], L52425 [E5]`

It might be just change in FirrtlProtos.java between the versions, but just in case it helps!

**Comment by jackkoenig** [comment]
There are a couple of things we can try.

1. Try deleting the directory with `FirrtlProtos.java` to ensure that Wake will rerun the job. It has no way of detecting the fact that you installed a new version of `protoc`, so it may not be using the stale value generated previously with a different version of `protoc`.

2. Are you certain that Wake is running the correct version of protoc? Wake isolates the user environment from the environment it uses to run jobs. You can see what environment Wake is using by typing `wake subscribe environment`. In my case:

```
jack@Jacks-MacBook-Pro:~/work/wake-experiment$ wake subscribe environment
"PATH=/opt/local/bin:/usr/local/bin:/usr/bin:/bin", Nil
jack@Jacks-MacBook-Pro:~/work/wake-experiment$ PATH=/opt/local/bin:/usr/local/bin:/usr/bin:/bin which protoc
/usr/local/bin/protoc
```
I will note that `Wake` includes `/usr/local/bin` in the `PATH` on Macs, but not on Linux.

**Comment by saurabhsingh-pvips** [comment]
Trying out the 2nd thing:
Firing `wake subscribe environment` results this:
```
saurabh@LAPTOP-1CDA1SBV:~/workspace$ wake subscribe environment
"PATH=/usr/bin:/bin", Nil
```
An observation I've made that `echo $PATH` gives me  `/usr/bin/protoc` as one of the paths while `which protoc` shows me this path: `/usr/local/bin/protoc/`.

I assume there's something to fix in here before trying out the first option you mentioned?

**UPDATE:**
Verifying the installation manually, `/usr/local/bin` has protoc but `/usr/bin/protoc` doesn't exist. I assume this is path mismatch due to some previous installation?

I added the protoc path to PATH variable and removed the directory containing `FirrtlProtos.java`. Re running the wake script again errors:

```
<ivycache> ivycache
protoc --java_out=build/firrtl/proto firrtl/src/main/proto/firrtl.proto
execve protoc: No such file or directory
/usr/bin/java -cp ivycache/https/repo1.maven.org/maven2/com/ibm/icu/icu4j/61.1/icu4j-61.1.jar:ivycache/https/repo1.maven.org/maven2/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/ST4/4.1/ST4-4.1.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/antlr4/4.7.2/antlr4-4.7.2.jar:ivycache/https/repo1.maven.org/maven2/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar org.antlr.v4.Tool -o build/firrtl/antlr -visitor -no-listener -package firrtl.antlr firrtl/src/main/antlr4/FIRRTL.g4
api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/rocketchipMacros.json.template -c build/api-scala-sifive/bloop/rocketchipMacros.json -b scala --coursier-cache ivycache --bloop-args compile -c build/api-scala-sifive/bloop rocketchipMacros --jar build/rocketchipMacros/scala-2.12/jar/rocketchipMacros.jar
api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/chisel3Macros.json.template -c build/api-scala-sifive/bloop/chisel3Macros.json -b scala --coursier-cache ivycache --bloop-args compile -c build/api-scala-sifive/bloop chisel3Macros --jar build/chisel3Macros/scala-2.12/jar/chisel3Macros.jar
WARNING: Could not parse DTS JSON: _root_.sifive.skeleton.DefaultConfig_sifive.skeleton.WithSimUART_sifive.skeleton.WithTestFinisher_sifive.blocks.pio.WithpioTop.json file not found
scripts/autoconf_wrapper --configure-args= --install-dir=../build/freedom-devicetree-tools
+ for i in "$@"
+ case $i in
+ CONFIGURE_ARGS=
+ shift
+ for i in "$@"
+ case $i in
+ INSTALL_DIR=../build/freedom-devicetree-tools
+ shift
+ autoreconf -i
+ ./configure --prefix=
+ make
++ pwd
+ make DESTDIR=/home/saurabh/workspace/freedom-devicetree-tools/../build/freedom-devicetree-tools install
PANIC: Error "File not found" Nil
Requirement !panic_called failed at src/exception.cpp:64
```
`execve protoc: No such file or directory` I did encounter this error previously too but resolved it by reinstalling protocbuf.

**Comment by jackkoenig** [comment]
With the goal of making build rules reproducible between different environments, wake isolates jobs from the users environment. When you did `wake subscribe environment`, it showed that the `PATH` Wake is using for jobs is `PATH=/usr/bin:/bin`, thus protoc won't be on the path because it's installed to `/usr/local/bin`.

The basic idea is that the location where tools like protobuf may vary from machine to machine, so if I write build rules on my Macbook and want it to work on an Ubuntu or Centos machine, I need to declare protobuf as a resource (as done [here](https://github.com/sifive/api-firrtl-sifive/blob/4977bbeeadc350e2e1290237d17dd1baf77013f8/build.wake#L29)) and then users of the `api-firrtl-sifive` need an _environment package_ to provide resources like protobuf.

There are two ways you can resolve this issue:

#### Hacky Workaround

Wake uses the environment variable `WAKE_PATH` to help workaround stuff like this. It will prepend anything on `WAKE_PATH` to the `PATH` it uses for running jobs. For example:

```
$ wake subscribe environment
"PATH=/usr/bin:/bin", Nil
$ WAKE_PATH=/some/path wake subscribe environment
"PATH=/some/path:/usr/bin:/bin", Nil
```

#### The Right Way (TM)

We have an example environment package https://github.com/sifive/environment-example-sifive
This allows you to provide PATH and other environment variables for resources like protobuf (and it even uses protobuf 3.5.1 as an example!) in a JSON format as described in the README. 

This is a lot to explain and we sorely need better documentation on this, so I'll give it a shot.

You can modify `environment-example-sifive` to provide protobuf as a resource for all jobs.

First, add it to your workspace
```bash
$ wit add-pkg https://github.com/sifive/environment-example-sifive.git
Adding package to workspace
Cloning environment-example-sifive...
The workspace now depends on 'environment-example-sifive::496b02f'

# Pull the added package into the workspace
$ wit update
Cloning python-semver...
Checking out 'python-semver' at 'tags/2.9.0' (1bafb9f0aea0117a196eb7d112c3f0a0da783abf)
```

Now we need to create a JSON that provides the PATH for protobuf:
```bash
# For you /usr/local/bin is the PATH, may be different for others
echo '{"google":{"protobuf":{"3.5.1":{"PATH":"/usr/local/bin"}}}}' > environment-example-sifive/env.json

# Don't forget to add the JSON to git! Wake only considers files known to git as legal source files
git -C environment-example-sifive add env.json
```

Now we need to "publish" this JSON in wake code so that it can be included as a resource provider:
```
echo 'publish environmentJSONs = source "{here}/env.json", Nil' > environment-example-sifive/publish.wake
```

That should do it! We can sanity check that this is properly working:
```bash
$ wake 'makePlan ("protoc", "--version", Nil) Nil | setPlanResources ("google/protobuf/3.5.1", Nil) | runJob | getJobStdout'
protoc --version
Pass "libprotoc 3.5.1\n"
```

This needs to be turned into a real tutorial, but hopefully this is helpful at least.

**Comment by saurabhsingh-pvips** [comment]
So you Right Way worked fine. I am pass that error but involved in other errors. Will raise a issue if needed.
