### ISSUE TITLE
initiliazing workspace with preonboarded branch is giving an error ! 

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/block-pio-sifive#45]
Hello,
At the beginning , during the initializing the workspace with the command : <code>wit init workspace1 -a git@github.com:sifive/block-pio-sifive.git::preonboarded</code> is giving an error like following:
<pre>Creating new workspace [/home/pvips-shraddha/workspace1]
Cloning block-pio-sifive...
[ERROR] Bad remote for &apos;block-pio-sifive&apos;:
  git@github.com:sifive/block-pio-sifive.git
</pre>
so, how can I resolve this?

**Comment by ShraddhaDevaiya** [comment]
Solved ! we need to update ssh key in our profile,which is same available to our machine , on which we are trying to clone .So, it was just that !

**Comment by usman1515** [comment]
A very noob question since I have just started using git and github. Can you tell me or point me in a direction on how and where to update the SSH key. Im using Ubuntu .

**Comment by richardxia** [comment]
Hi, you may find GitHub's documentation on SSH keys useful: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
