### ISSUE TITLE
'wake makeOnboardingDocument pioDUT' is giving an error ! 

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/block-pio-sifive#47]
In the tutorial of preonboarded branch, during the creation of Onboarding document, we have entered this command : <code> wake makeOnboardingDocument pioDUT</code> and it fires the following error:
<pre><font color="#8AE234"><b>shraddha@terminal</b></font>:<font color="#729FCF"><b>~/workspace</b></font>$ wake makeOnboardingDocument pioDUT 
&lt;ivycache&gt; ivycache
/bin/cp scribble/Pipfile.lock build/scribble/Pipfile.lock
/bin/cp scribble/Pipfile build/scribble/Pipfile
protoc --java_out=build/firrtl/proto firrtl/src/main/proto/firrtl.proto
/usr/bin/java -cp ivycache/https/repo1.maven.org/maven2/com/ibm/icu/icu4j/61.1/icu4j-61.1.jar:ivycache/https/repo1.maven.org/maven2/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/ST4/4.1/ST4-4.1.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar:ivycache/https/repo1.maven.org/maven2/org/antlr/antlr4/4.7.2/antlr4-4.7.2.jar:ivycache/https/repo1.maven.org/maven2/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar org.antlr.v4.Tool -o build/firrtl/antlr -visitor -no-listener -package firrtl.antlr firrtl/src/main/antlr4/FIRRTL.g4
api-languages-sifive/install-python-pipenv build/scribble/Pipfile build/scribble/Pipfile.lock build/scribble/.venv
api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/rocketchipMacros.json.template -c build/api-scala-sifive/bloop/rocketchipMacros.json -b scala --coursier-cache ivycache --bloop-args compile -c build/api-scala-sifive/bloop rocketchipMacros --jar build/rocketchipMacros/scala-2.12/jar/rocketchipMacros.jar
api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/chisel3Macros.json.template -c build/api-scala-sifive/bloop/chisel3Macros.json -b scala --coursier-cache ivycache --bloop-args compile -c build/api-scala-sifive/bloop chisel3Macros --jar build/chisel3Macros/scala-2.12/jar/chisel3Macros.jar
api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/firrtl.json.template -c build/api-scala-sifive/bloop/firrtl.json -b scala --coursier-cache ivycache --bloop-args compile -c build/api-scala-sifive/bloop firrtl --jar build/firrtl/scala-2.12/jar/firrtl.jar
<font color="#CC0000">Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.</font>
<font color="#CC0000">PANIC: Hash mismatch for build/scribble/.venv/bin/activate (6c509b20b5a3b06d3b229188917b5ced81251f90284f0e117998926dfd165fbc != 04b632bec64f7157715b61581bdfbe051f4e6b22416c2f79c49e3b8446acd3b2); remove it</font>
<font color="#CC0000">Requirement !panic_called failed at src/exception.cpp:64</font>
<font color="#8AE234"><b>shraddha@terminal</b></font>:<font color="#729FCF"><b>~/workspace</b></font>$ 
</pre>

So how can I resolve this?

**Comment by ShraddhaDevaiya** [comment]
Now , previously mentioned error gone and coming the following error:
 <pre>&lt;ivycache&gt; ivycache
python3.7 -B -m scribble.document --output build/api-generator-sifive/pioDUT/documents/pioDUT.adoc --sections document.Onboarding --design-file build/api-generator-sifive/pioDUT/documents/design.json --values product_name=pioDUT Test Socket
<font color="#CC0000">Traceback (most recent call last):</font>
<font color="#CC0000">  File &quot;/usr/lib/python3.7/runpy.py&quot;, line 193, in _run_module_as_main</font>
<font color="#CC0000">    &quot;__main__&quot;, mod_spec)</font>
<font color="#CC0000">  File &quot;/usr/lib/python3.7/runpy.py&quot;, line 85, in _run_code</font>
<font color="#CC0000">    exec(code, run_globals)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/document.py&quot;, line 225, in &lt;module&gt;</font>
<font color="#CC0000">    main()</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/document.py&quot;, line 190, in main</font>
<font color="#CC0000">    values=args.values,</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/document.py&quot;, line 71, in document</font>
<font color="#CC0000">    for text in Section(section, doc, **context):</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble-testsocket-sifive/docs/scribble/document/Onboarding/Onboarding.py&quot;, line 58, in Onboarding</font>
<font color="#CC0000">    **context</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/section.py&quot;, line 170, in PairedTemplate</font>
<font color="#CC0000">    text = template(file_name, scope=scope, kwargs=newargs, **newargs)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/template.py&quot;, line 41, in template</font>
<font color="#CC0000">    text = templ.render(**kwargs, **GLOBALS)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/asyncsupport.py&quot;, line 76, in render</font>
<font color="#CC0000">    return original_render(self, *args, **kwargs)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/environment.py&quot;, line 1008, in render</font>
<font color="#CC0000">    return self.environment.handle_exception(exc_info, True)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/environment.py&quot;, line 780, in handle_exception</font>
<font color="#CC0000">    reraise(exc_type, exc_value, tb)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/_compat.py&quot;, line 37, in reraise</font>
<font color="#CC0000">    raise value.with_traceback(tb)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble-testsocket-sifive/docs/scribble/document/Onboarding/Onboarding.jinja2&quot;, line 24, in top-level template code</font>
<font color="#CC0000">    {{ Snippet(&quot;Programming&quot;, devices[0], devices=devices, **kwargs)  }}</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/section.py&quot;, line 141, in Snippet</font>
<font color="#CC0000">    return fn()</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/section.py&quot;, line 112, in &lt;lambda&gt;</font>
<font color="#CC0000">    lambda: Text(fn(scope, _curpath_=path, _file_=module.__file__, **kwargs)),</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble-testsocket-sifive/docs/scribble/components/Component/Programming.jinja2&quot;, line 7, in Programming</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/template.py&quot;, line 41, in template</font>
<font color="#CC0000">    text = templ.render(**kwargs, **GLOBALS)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/asyncsupport.py&quot;, line 76, in render</font>
<font color="#CC0000">    return original_render(self, *args, **kwargs)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/environment.py&quot;, line 1008, in render</font>
<font color="#CC0000">    return self.environment.handle_exception(exc_info, True)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/environment.py&quot;, line 780, in handle_exception</font>
<font color="#CC0000">    reraise(exc_type, exc_value, tb)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/_compat.py&quot;, line 37, in reraise</font>
<font color="#CC0000">    raise value.with_traceback(tb)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble-testsocket-sifive/docs/scribble/components/Component/Programming.jinja2&quot;, line 6, in top-level template code</font>
<font color="#CC0000">    {{ Section(&quot;.RegisterList&quot;, scope, **kwargs) }}</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/section.py&quot;, line 70, in Section</font>
<font color="#CC0000">    return fn()</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/section.py&quot;, line 112, in &lt;lambda&gt;</font>
<font color="#CC0000">    lambda: Text(fn(scope, _curpath_=path, _file_=module.__file__, **kwargs)),</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble-testsocket-sifive/docs/scribble/components/Component/RegisterList.jinja2&quot;, line 7, in RegisterList</font>
<font color="#CC0000">    {{ registers.table(title=&quot;{} Register Map&quot;.format(scope._type)) }}</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble/scribble/template.py&quot;, line 41, in template</font>
<font color="#CC0000">    text = templ.render(**kwargs, **GLOBALS)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/asyncsupport.py&quot;, line 76, in render</font>
<font color="#CC0000">    return original_render(self, *args, **kwargs)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/environment.py&quot;, line 1008, in render</font>
<font color="#CC0000">    return self.environment.handle_exception(exc_info, True)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/environment.py&quot;, line 780, in handle_exception</font>
<font color="#CC0000">    reraise(exc_type, exc_value, tb)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/build/scribble/.venv/lib/python3.7/site-packages/jinja2/_compat.py&quot;, line 37, in reraise</font>
<font color="#CC0000">    raise value.with_traceback(tb)</font>
<font color="#CC0000">  File &quot;/home/pvips-shraddha/workspace/.fuse/18283/scribble-testsocket-sifive/docs/scribble/components/Component/RegisterList.jinja2&quot;, line 7, in top-level template code</font>
<font color="#CC0000">    {{ registers.table(title=&quot;{} Register Map&quot;.format(scope._type)) }}</font>
<font color="#CC0000">TypeError: table() got an unexpected keyword argument &apos;title&apos;</font>
Fail (Error &quot;Scribble failed to produce output file build/api-generator-sifive/pioDUT/documents/pioDUT.adoc&quot; Nil)
</pre>
So what is it ?

**Comment by albertchen-sifive** [comment]
@richardxia @john-sifive can you answer this? I'm not familiar with the scribble flow. this also seems related to https://github.com/sifive/block-pio-sifive/issues/46 (see update 3)

**Comment by john-sifive** [comment]
We changed the parameter from "title" to "caption" for the register map tables. All the other tables and figures use the parameter name "title".  Since the default block-pio document doesn't include a register map,  I think this user has added a register map and gotten confused about the parameter name.

I'm going to suggest they change the parameter to "caption", but we should be consistent in our code - use either "title" or "caption" across the board. Asciidoctor refers to it as "title", so I'm in favor of changing "caption" back to "title".  (We'll probably need to add both for backwards compatibility)

Here's an example from the AsciiDoc reference
```
.Table Title
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3 

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===
```

**Comment by john-sifive** [comment]
Update - that error is in the jinja template  components/Component/RegisterMap.jinja2 - the confusion is ours, not Shraddha's.

**Comment by richardxia** [comment]
> Asciidoctor refers to it as "title", so I'm in favor of changing "caption" back to "title".

I just looked it up in their documentation, and it appears that a title and a caption are two separate, but related concepts: https://asciidoctor.org/docs/user-manual/#table-caption. Confusingly enough, they also mention that the special attribute named `caption` actually only affects the prefix of the caption line.

I agree with your assessment that the field that we are emitting in the .adoc is called a title, so we should probably call it that.

@john-sifive, do you think you could make a quick change to fix this?

**Comment by ShraddhaDevaiya** [comment]
But if it has some issue with "title" or "caption", then why  is it not emitting error with master branch and in preonboarded branch only? I already checked with master branch , it is working and generating the document properly.

**Comment by richardxia** [comment]
The code that contains the bug is not exercised on the master branch of block-pio-sifive because the buggy code only exists as a placeholder for blocks which haven't defined that chapter. If you create a new block and do not override the placeholder template, then you run into this issue. We're working on having this fixed soon.

**Comment by john-sifive** [comment]
Note: Fixed in scribble-testsocket-sifive v0.1.2.  

Recommend updating to use latest repository for block-pio-sifive. The manifests should bring in the fixed version. Alternatively, bring in the latest scribble-testsocket-sifive.

**Comment by saurabhsingh-pvips** [comment]
Checked out the tag `v0.1.2` . The is resolved but build stucks on yet another error:
```
raise DocumentException(f"The {device._type} does not have any registers defined") 
scribble.exceptions.DocumentException: The loopback does not have any registers defined 
```
Looks like scribble expects register definitions in loopback.json5 similar to as how defined in pio.json5.

Complete error message: 
[loopback_no_register_error.log](https://github.com/sifive/block-pio-sifive/files/4029194/loopback_no_register_error.log)


Comments?

**Comment by albertchen-sifive** [comment]
sorry, there was an error in the instructions for the scala code. please try updating the `wit-manifest.json` and the `pio.scala` file to reflect the changes in this PR https://github.com/sifive/block-pio-sifive/pull/61/files

**Comment by hirensolankipvips** [comment]
Issue resolved.

Successfully created **_pioDUT.adoc_** and **_pioDUT.html_**

**Comment by ShraddhaDevaiya** [comment]
@hirensolankipvips  issue is with preonboarded branch , not with the master branch. So, for which branch , it worked for you, is it master branch or preonboarded branch?

**Comment by ShraddhaDevaiya** [comment]
Okay, thanks will check it again!
