### ISSUE TITLE
Error: unknown CSR `mtvt. 'wake runSimWith pioDUT Verilator' fails.

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#55]
Error Message: 
```
src/drivers/riscv_cpu.c: Assembler messages:
src/drivers/riscv_cpu.c:144: Error: unknown CSR `mtvt'
src/drivers/riscv_cpu.c:166: Error: unknown CSR `mtvt'
src/drivers/riscv_cpu.c:170: Error: unknown CSR `mtvt'
make[1]: *** [src/drivers/libriscv__mmachine__pioDUT_a-riscv_cpu.o] Error 1
make: *** [all] Error 2
```
When I `grep` mtvt in the workspace, `/rocket-chip/src/main/scala/rocket/Instructions.scala:795:` has the definition `val mtvt = 0x307` already defined.

**Comment by albertchen-sifive** [comment]
what version of the riscv toolchain are you using? We require that you use the toolchain from https://github.com/sifive/freedom-metal/issues/78

**Comment by saurabhsingh-pvips** [comment]
The fix helped. Using the toolchain from the link mentioned does the job. Thanks!
