### ISSUE TITLE
'wake runSim pioDUT' fails to compile firrtl

### ISSUE THREAD

**Issue by ishitapvips** [sifive/block-pio-sifive#56]
hi,
When I run the command <code> wake runSim pioDUT </code>
It throws the following error
<pre>
[E] [E5] ../../firrtl/src/main/scala/firrtl/proto/FromProto.scala:308:22
[E]      value hasExternalModule is not a member of firrtl.FirrtlProtos.Firrtl.Module
[E]      L308:       require(module.hasExternalModule, "Module must have Module or ExtModule")
[E]                                 ^
[E] [E4] ../../firrtl/src/main/scala/firrtl/proto/FromProto.scala:306:16
[E]      value hasUserModule is not a member of firrtl.FirrtlProtos.Firrtl.Module
[E]      L306:     if (module.hasUserModule) convert(module.getUserModule)
[E]                           ^
[E] ../../firrtl/src/main/scala/firrtl/RenameMap.scala: L76 [E1], L77 [E2], L78 [E3]
[E] ../../firrtl/src/main/scala/firrtl/proto/FromProto.scala: L306 [E4], L308 [E5]
[E] 'firrtl' failed to compile.
Scala compilation failed for 'api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/firrtl.json.template -c build/api-scala-sifive/bloop/firrtl.json -b scala --coursier-cache ivycache --bloop-args "compile -c build/api-scala-sifive/bloop firrtl" --jar build/firrtl/scala-2.12/jar/firrtl.jar'
</pre>
How can I resolve this?

**Comment by jackkoenig** [comment]
I believe this comes from too old of a version of `protoc`, I'm guessing this is ~3.0.0 when you need 3.5.0-3.7.1

We generally solve this by getting the right protoc version from here: https://github.com/protocolbuffers/protobuf/releases/tag/v3.5.1. Assuming Linux, you can get the Linux-agnostic binary `protoc-3.5.1-linux-x86_64.zip` from that release page.

You then should make an environment module based on https://github.com/sifive/environment-example-sifive (either make a new repo that has a wit dependency on it, or just fork it), and fill in an environment JSON file as described in the README that points to the protoc install.

We're working on making this environment aspect of the flow a bit more automated and portable, but it's a hard problem 🙂

**Comment by ishitapvips** [comment]
Thanks for the help It worked after installing the 3.5.1 version of the protoc
