### ISSUE TITLE
Inappropriate pio-diagram.svg causing text to disappear when exported to .pdf 

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#57]
The pdf of onboarding documentation when exported with asciidoctor-pdf has text missing in the block diagram:

![image](https://user-images.githubusercontent.com/57518239/70965342-61c9b580-20b5-11ea-82c1-d96aad6132b9.png)

The issues at first seemed to be of [prawn-svg](https://github.com/mogest/prawn-svg) so I filed the issue [here](https://github.com/mogest/prawn-svg/issues/113). 

The issue in actual seems to be use of a recommended approach in generating the svg file as described in this [comment](https://github.com/mogest/prawn-svg/issues/113#issuecomment-566169536).

**Comment by richardxia** [comment]
Hi @saurabhsingh-pvips, thanks for reporting this. Unfortunately, this particular diagram was created in [Lucidchart](https://www.lucidchart.com/), but I don't think we'll be able to control the SVG export process that well. Given that it is technically a valid SVG file, even though it's not a recommended ordering, I'm not sure if Lucidchart would change the export method.

I think it would be acceptable, to manually edit this SVG file to put the `<def>`s higher up, but the caveat is that if we do another export from Lucidchart, they may end up in a different order again.
