### ISSUE TITLE
Panic: Error occurs while running 'wake  runSim pioDUT' commands  

### ISSUE THREAD

**Issue by ishitapvips** [sifive/block-pio-sifive#58]
Hi,
while running <code> wake runSim pioDUT </code>. It throws the following error
<pre>
PANIC: Error "gcc: could not find output file: build/api-generator-sifive/pioDUT/programs/demo/demo.elf" Nil
Requirement !panic_called failed at src/exception.cpp:69
ishita@DESKTOP-B4D4E03:~/workspace$
</pre>

How do I fix this?

**Comment by albertchen-sifive** [comment]
can you show the full log? It's hard to tell what the problem is just from these lines.

**Comment by ishitapvips** [comment]
These are the warnings:

```
+ set -e
+ '[' 7 -ne 7 ']'
+ host=riscv64-unknown-elf
+ machine_name=pioDUT
+ machine_header=../pioDUT.h
+ machine_inline=../pioDUT-inline.h
+ platform_header=../pioDUT-platform.h
+ machine_ldscript=../pioDUT.lds
+ install_dir=..
++ pwd
+ machine_header=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT.h
++ pwd
+ machine_inline=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT-inline.h
++ pwd
+ platform_header=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT-platform.h
++ pwd
+ machine_ldscript=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT.lds
++ pwd
+ install_dir=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/..
+ export RISCV_PATH=
+ RISCV_PATH=
+ autoreconf -i
+ ./configure --host=riscv64-unknown-elf --disable-maintainer-mode --with-preconfigured --with-machine-inline --with-platform-header --with-machine-name=pioDUT --with-machine-header=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT.h --with-machine-inline=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT-inline.h --with-platform-header=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT-platform.h --with-machine-ldscript=/home/ishita/workspace/build/freedom-metal/pioDUT/freedom-metal/../pioDUT.lds --with-builtin-libgloss --prefix=
+ make 'RANLIB=riscv64-unknown-elf-ranlib -D' ARFLAGS=Dcr
src/drivers/fixed-clock.c: In function '__metal_driver_fixed_clock_get_rate_hz':
src/drivers/fixed-clock.c:14:44: warning: passing argument 1 of '__metal_driver_fixed_clock_rate' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     return __metal_driver_fixed_clock_rate(gclk);
                                            ^~~~
In file included from src/drivers/fixed-clock.c:10:
./metal/machine.h:105:81: note: expected 'struct metal_clock *' but argument is of type 'const struct metal_clock *'
 static inline unsigned long __metal_driver_fixed_clock_rate(struct metal_clock *clock)
                                                             ~~~~~~~~~~~~~~~~~~~~^~~~~
ar: creating VTestDriver__ALL.a
```
Find the log here.
[log.txt](https://github.com/sifive/block-pio-sifive/files/3979732/log.txt)

**Comment by richardxia** [comment]
Hi @ishitapvips, sorry for the delay. It seems like freedom-metal is not successfully compiling for you. Could you list the versions of Wit packages in your workspace to help us identify the specific versions being used? You can do this by uploading the contents of `wit-lock.json`, which can be found at the root directory of the workspace.

**Comment by ishitapvips** [comment]
Hi @richardxia , 
Please find the content of wit-lock.json file
[wit-lock.txt](https://github.com/sifive/block-pio-sifive/files/4021534/wit-lock.txt)

**Comment by albertchen-sifive** [comment]
hi @ishitapvips 
can you rerun that command but with the `-v` flag e.g. `wake -v 'runSim pioDUT'` and post the log (the `-v` flag will tell wake to output stdout in addition to stderr). also are you sure you have published an environment json with an entry for `riscv-tools/2019.05.0` like this one https://github.com/sifive/environment-blockci-sifive/blob/better-json-environment-runner/environment.json. you'll also need a wake file that publishes that path like this https://github.com/sifive/environment-blockci-sifive/blob/better-json-environment-runner/wake/environment.wake

**Comment by ishitapvips** [comment]
Hi @albertchen-sifive  
Firstly I didn't publish environment json as I was using environment-sanmateo . After publishing also It is giving same as above error
I have attached both the logs
[log.txt](https://github.com/sifive/block-pio-sifive/files/4029221/log.txt)


[log_with_envjson.txt](https://github.com/sifive/block-pio-sifive/files/4029230/log_with_envjson.txt)

**Comment by ishitapvips** [comment]
Resolved with updating the drivers/metals version v0.1.0.
