### ISSUE TITLE
wake 'runSim pioDUT' command giving an error in master branch!

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/block-pio-sifive#60]
Hello, command mentioned in the subject is giving an error and compilation log with error for that is following:
[compilation_log.log](https://github.com/sifive/block-pio-sifive/files/4001425/compilation_log.log)

**Comment by saurabhsingh-pvips** [comment]
Line 72: `configure: error: C compiler cannot create executables` , looks like issue with GNU-toolchain.

**Comment by ShraddhaDevaiya** [comment]
Resolved it!
