### ISSUE TITLE
Query: Significance of "baseAddress" while describing memory map.

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/block-pio-sifive#68]
I am not sure what's the significance of `baseAddress` defined in `pio.json5`.

Going through the scripts of `duh-export-scala`, I realize `baseAddress` has no role to play. The scala generated as a result don't have the mention of any `baseAddress` for the memory map.

However, the `duh-export-regmap` makes use of `baseAddress` and it reflects in the output of this script.

My query is twofold:
1) Is there any significance of `baseAddress` when I define my register map. If yes, where do I see the difference `baseAddress` makes? If no, at what memory location does the registers rest?

2) What is the use case of `duh-export-regmap`. Is it a must in order to access and configure registers using let's say `apb bus` ?

**Comment by richardxia** [comment]
@drom, could you answer @saurabhsingh-pvips's question about `baseAddress`? I am also unclear about the purpose of the `baseAddress` property in the DUH document.


Regarding `duh-export-regmap`, that is only meant for creating a Chisel `RegisterRouter` instance, which is an AMBA- or TileLink-addressable set of registers which can then be connected to a block of logic. You do not need to use that if the block itself already has memory-mapped registers implemented within the design. See https://github.com/sifive/duh-scala/blob/5aedd4129be449f51547c8a4813dd27891c19912/README.md#exporting-a-registerrouter for more information about `duh-export-regmap`.

**Comment by drom** [comment]
`baseAddress` specifies the starting address of the address space. The address space numbering normally starts at 0. Some address spaces may use offset addressing (starting at a number other than 0) so the base address element can be used to designate this information.

Agree, that `baseAddress` should be used by `duh-scala` and construct Object Model.

**Comment by saurabhsingh-pvips** [comment]
@drom 
So is the understanding correct that the `baseAddress` described in duh document should be same as what is mentioned in exported scala? Like in pio's case, the `baseAddress` for bus as `ctrl_base` mentioned in class `WithpioTop` in the file `pio.scala`. Or do these two addresses point to different entities?
